### ISSUE TITLE
mvc

### ISSUE THREAD

**Issue by ifredom** [51nb/miox#4]
没有过多深入，用了用路由，发现似乎属于mvc而不是mvvc？纯前端er用起来可能要费事一点。

**Comment by cevio** [comment]
@ifredom [https://www.zhihu.com/question/68308785/answer/263313978](https://www.zhihu.com/question/68308785/answer/263313978) 可以看下这里。有非常详细的介绍核心路由的功能点。同时可以看下[https://github.com/51nb/miox-demo-basic-use](https://github.com/51nb/miox-demo-basic-use)这个demo，演示了基本的路由使用。
